### ISSUE TITLE
Doctests fail on Python 3

### ISSUE THREAD

**Issue by olebole** [spacetelescope/asdf#447]
Hi,

when disabling the remote tests (#429), I experienced failures in the doctests with Python 3 (3.6.4):
```
=================================== FAILURES ===================================
_________________________ [doctest] asdf.stream.Stream _________________________
010 
011     Used to put a streamed array into the tree.
012 
013     Examples
014     --------
015     Save a double-precision array with 1024 columns, one row at a
016     time::
017 
018          >>> from .asdf import AsdfFile, Stream
UNEXPECTED EXCEPTION: ImportError("cannot import name 'Stream'",)
Traceback (most recent call last):

  File "/usr/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest asdf.stream.Stream[0]>", line 1, in <module>

ImportError: cannot import name 'Stream'

/tmp/asdf-test-bpib0yoa/lib/python3.6/site-packages/asdf/stream.py:18: UnexpectedException
____________________ [doctest] asdf.util.InheritDocstrings _____________________
340 
341     If the class uses multiple inheritance, the docstring will be
342     chosen from the first class in the bases list, in the same way as
343     methods are normally resolved in Python.  If this results in
344     selecting the wrong docstring, the docstring will need to be
345     explicitly included on the method.
346 
347     For example::
348 
349         >>> from .asdf.util import InheritDocstrings
UNEXPECTED EXCEPTION: ModuleNotFoundError("No module named 'asdf.asdf.util'; 'asdf.asdf' is not a package",)
Traceback (most recent call last):

  File "/usr/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest asdf.util.InheritDocstrings[0]>", line 1, in <module>

ModuleNotFoundError: No module named 'asdf.asdf.util'; 'asdf.asdf' is not a package

/tmp/asdf-test-bpib0yoa/lib/python3.6/site-packages/asdf/util.py:349: UnexpectedException
```
With Python 2.7, this runs fine.

**Comment by drdavella** [comment]
Thanks for the report. Which version of ASDF were you using?

**Comment by olebole** [comment]
That is the latest version, 1.3.1, taken from pypi.

**Comment by drdavella** [comment]
@olebole I just released `v1.3.2`, which I hope resolves this issue. Please reopen with the full test output log if you encounter it again.

**Comment by olebole** [comment]
Unfortunately, I still run into this problem.
```
=================================== FAILURES ===================================
_________________________ [doctest] asdf.stream.Stream _________________________
010 
011     Used to put a streamed array into the tree.
012 
013     Examples
014     --------
015     Save a double-precision array with 1024 columns, one row at a
016     time::
017 
018          >>> from .asdf import AsdfFile, Stream
UNEXPECTED EXCEPTION: ImportError("cannot import name 'Stream'",)
Traceback (most recent call last):

  File "/usr/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest asdf.stream.Stream[0]>", line 1, in <module>

ImportError: cannot import name 'Stream'

/tmp/asdf-test-djngyzi3/lib/python3.6/site-packages/asdf/stream.py:18: UnexpectedException
____________________ [doctest] asdf.util.InheritDocstrings _____________________
340 
341     If the class uses multiple inheritance, the docstring will be
342     chosen from the first class in the bases list, in the same way as
343     methods are normally resolved in Python.  If this results in
344     selecting the wrong docstring, the docstring will need to be
345     explicitly included on the method.
346 
347     For example::
348 
349         >>> from .asdf.util import InheritDocstrings
UNEXPECTED EXCEPTION: ModuleNotFoundError("No module named 'asdf.asdf.util'; 'asdf.asdf' is not a package",)
Traceback (most recent call last):

  File "/usr/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest asdf.util.InheritDocstrings[0]>", line 1, in <module>

ModuleNotFoundError: No module named 'asdf.asdf.util'; 'asdf.asdf' is not a package

/tmp/asdf-test-djngyzi3/lib/python3.6/site-packages/asdf/util.py:349: UnexpectedException
```

**Comment by drdavella** [comment]
Can you please post the entire test output log here, along with steps to reproduce? I have tested this on a Debian system but obviously there is something different in our environments.

**Comment by olebole** [comment]
Sure...
[python-asdf_1.3.2-1_amd64.txt](https://github.com/spacetelescope/asdf/files/1749306/python-asdf_1.3.2-1_amd64.txt)

**Comment by drdavella** [comment]
@olebole I still can't reproduce this issue in my Debian VM. I noticed that you're not running the tests from within a virtual environment, is that correct? If so, I suspect that what's happening is that you have an older version of `asdf` installed in your system site-packages, and the tests are somehow running against that older version of `asdf` instead of against the latest version.

The main clue for me is that if you grep for the string `from .asdf import AsdfFile, Stream` in the current release, you won't find it anywhere. This suggests at the very least that the tests aren't running against the right version.

**Comment by drdavella** [comment]
I'm not sure how to account for this error, then, since the offending source line is not the same in the distributed package. In fact, looking at the git blame, both of these lines were last updated by you in 2016:

https://github.com/spacetelescope/asdf/commit/22aa33461e72f19aacb88f81297d4772191546a0#diff-5432019af3c0c975c035a5bdd0c381fd

**Comment by olebole** [comment]
It seems that the 1.3.2 release **was not done** at the master branch: 
[This](https://github.com/spacetelescope/asdf/blob/v1.3.2/asdf/util.py#L13-L16) is `asdf/util.py` in 1.3.2; still containing the lines `from six.moves...`.
[This](https://github.com/spacetelescope/asdf/blob/6b937c0ba1b1d151c946d483f99379a2b3505c63/asdf/util.py) is the `master` `HEAD`, which does not have these lines.

Could this cause the problem?

**Comment by drdavella** [comment]
You're right, it was not done from the `master` branch. I'm also preparing for a `2.0.0` release and `1.3.2` was released as a bugfix to the `1.3.x` branch. The current release should be reflected on `stable`.

However, the lines you provided **do not match**. Critically, the lines in your failing tests say `from .asdf`, whereas the source lines in the packaged release say `from asdf`. The critical difference is the presence of the dot `.`. If I change these lines in my source checkout to add the dot, then I get the same failures you do. This is getting really bizarre, though.

**Comment by olebole** [comment]
The difference comes from six which is appliedby `setup.py`  before. The problem appears with Python 3.6.

**Comment by drdavella** [comment]
I'm not sure I understand what you mean b "the difference comes from six". Can please clarify? I have tested with Python 3.6 and can't reproduce.

**Comment by olebole** [comment]
My log file contains the lines
```
python3.6 setup.py test -vv --args -v
running test
running install
running build
running build_py
creating build/lib
creating build/lib/asdf
copying asdf/yamlutil.py -> build/lib/asdf
[...]
copying asdf-standard/reference_files/1.0.0/float.yaml -> build/lib/asdf/reference_files/1.0.0
Fixing build/lib/asdf/yamlutil.py build/lib/asdf/conftest.py build/lib/asdf/block.py build/lib/asdf/resolver.py build/lib/asdf/util.py [...] build/lib/asdf/commands/tests/__init__.py
Skipping optional fixer: buffer
Skipping optional fixer: idioms
Skipping optional fixer: set_literal
Skipping optional fixer: ws_comma
Fixing build/lib/asdf/yamlutil.py build/lib/asdf/conftest.py build/lib/asdf/block.py build/lib/asdf/resolver.py build/lib/asdf/util.py [...] build/lib/asdf/commands/tests/__init__.py
Skipping optional fixer: buffer
Skipping optional fixer: idioms
Skipping optional fixer: set_literal
Skipping optional fixer: ws_comma
running install_lib
creating /tmp/asdf-test-4y_6d22o/lib
[...]
```
where the fixing comes from 2to3 (not from six; my mistake). I don't know why 2to3 is involved here.

The problem seems to be connected to astropy-helpers: I use the system provided one (which is 3.0 for Python 3 in Debian unstable), and disable it in setup.cfg:

```
[ah_bootstrap]
auto_use = False
```

When I set this to `True`, the tests succeed.

So, I am just not sure whether this is a bug in astropy-helpers or in asdf?

**Comment by drdavella** [comment]
Oh man that is really weird. Does doing that fix the bug you reported in #429 as well? I realize I'm a bit on the defensive here, but you're going to have a very hard time convincing me this is a bug with ASDF, and not a weird artifact of the way your build works. Can you modify your build script so that this problem is resolved?

**Comment by drdavella** [comment]
Actually, would it fix the issue if I set `use_2to3=False`? I already did this on the development branch, but it didn't occur to me that it might need to be backported to `1.3.x`.

**Comment by olebole** [comment]
Using the asdf-provided astropy-helpers does not solve #429.

Setting `use_2to3=False` in `setup.py` indeed solves the problem (and is probably the right solution). But, doesn't do the lines 
```
def requires_2to3():  # pragma: no cover
    return False
```
in `asdf/setup_package.py` the same?

In principle I can live with the change in `setup.py`. However, I am not sure if this is a bug in astropy-helpers and I should create a bug there. Any thoughts?

**Comment by drdavella** [comment]
Hmm, good point. The `use_2to3` flag belongs to `setuptools`, but I think the `requires_2to3` function is specific to the astropy package template, right? So it's possible that they have different effects, but I'm not entirely sure. In any case, I think I removed both on the latest development branch, so I'll do the same here.

I don't think there's any need to create a bug in astropy helpers right now. They were clear that `use_2to3` would no longer be compatible with the helpers. The problem is that I didn't backport this change to the `1.3.x` release series. I'll make a patch and then will try to make a release early next week.

As for #429, I'm still at a loss since I can't reproduce it. But I'll keep poking around.

**Comment by olebole** [comment]
Ahh, now it becomes clear: [astropy-helpers/CHANGES.RST](https://github.com/astropy/astropy-helpers/blob/defebbf96e839f08af7c3412aacb0ad4f2404ca6/CHANGES.rst)
```
- Removing Python 2 support, including 2to3. Packages wishing to keep Python
  2 support should NOT update to this version. [#340]
```
That becomes ugly for me...

**Comment by drdavella** [comment]
Ah interesting. For this bugfix release I made sure to update to the latest version of the helpers that supports Py2.

Just curious, but is it easy for you to test your build either from github and/or from a source tarball before I publish to PyPI? That way I could make sure the 1.3.3 release actually fixes the issue.

**Comment by olebole** [comment]
I can download from github as well; for a release I would prefer a pypi version.

**Comment by drdavella** [comment]
Makes sense. Once #462 is merged would you be willing to check out the `v1.3.x` branch and run the tests again to see how we're doing? Maybe #429 will magically be resolved with the updates too...

**Comment by olebole** [comment]
Yes, sure. I may take over the weekend, however...

**Comment by drdavella** [comment]
@olebole this should now be fixed on `stable`. I'm about to issue a new release.

**Comment by olebole** [comment]
Thank you very much! I will test it tomorrow.

**Comment by olebole** [comment]
I can confirm that this bug and #429 is fixed with the version 1.3.3 in github. Would you mind to release this on pypi? It would better fit into my official Debian workflow (which includes PGP signature checking etc.).

**Comment by drdavella** [comment]
That's great! It should be there already: https://pypi.org/project/asdf/#files
